# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\moonbot\dev\storyTime\design\qt_ui.ui'
#
# Created: Tue Jun 28 12:36:18 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(621, 552)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView_2 = QtGui.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.verticalLayout.addWidget(self.graphicsView_2)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.timeLabel = QtGui.QLabel(self.centralwidget)
        self.timeLabel.setMinimumSize(QtCore.QSize(58, 0))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.timeLabel.setFont(font)
        self.timeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_3.addWidget(self.timeLabel)
        self.timeSlider = QtGui.QSlider(self.centralwidget)
        self.timeSlider.setProperty("value", 0)
        self.timeSlider.setSliderPosition(0)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.horizontalLayout_3.addWidget(self.timeSlider)
        self.recordBtn = QtGui.QPushButton(self.centralwidget)
        self.recordBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.recordBtn.setObjectName("recordBtn")
        self.horizontalLayout_3.addWidget(self.recordBtn)
        self.playBtn = QtGui.QPushButton(self.centralwidget)
        self.playBtn.setMaximumSize(QtCore.QSize(50, 16777215))
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout_3.addWidget(self.playBtn)
        self.curTimeLabel = QtGui.QLabel(self.centralwidget)
        self.curTimeLabel.setMinimumSize(QtCore.QSize(60, 0))
        self.curTimeLabel.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.curTimeLabel.setFont(font)
        self.curTimeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.curTimeLabel.setObjectName("curTimeLabel")
        self.horizontalLayout_3.addWidget(self.curTimeLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtGui.QSpacerItem(70, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.timingBox = QtGui.QCheckBox(self.centralwidget)
        self.timingBox.setMinimumSize(QtCore.QSize(0, 0))
        self.timingBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.timingBox.setChecked(True)
        self.timingBox.setObjectName("timingBox")
        self.horizontalLayout.addWidget(self.timingBox)
        self.audioBox = QtGui.QCheckBox(self.centralwidget)
        self.audioBox.setMaximumSize(QtCore.QSize(82, 16777215))
        self.audioBox.setChecked(True)
        self.audioBox.setObjectName("audioBox")
        self.horizontalLayout.addWidget(self.audioBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 621, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuFPS = QtGui.QMenu(self.menuOptions)
        self.menuFPS.setObjectName("menuFPS")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_Image_Sequence = QtGui.QAction(MainWindow)
        self.actionImport_Image_Sequence.setObjectName("actionImport_Image_Sequence")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.action24 = QtGui.QAction(MainWindow)
        self.action24.setCheckable(True)
        self.action24.setChecked(True)
        self.action24.setObjectName("action24")
        self.action25 = QtGui.QAction(MainWindow)
        self.action25.setCheckable(True)
        self.action25.setObjectName("action25")
        self.action30 = QtGui.QAction(MainWindow)
        self.action30.setCheckable(True)
        self.action30.setObjectName("action30")
        self.action48 = QtGui.QAction(MainWindow)
        self.action48.setCheckable(True)
        self.action48.setObjectName("action48")
        self.action50 = QtGui.QAction(MainWindow)
        self.action50.setCheckable(True)
        self.action50.setObjectName("action50")
        self.action60 = QtGui.QAction(MainWindow)
        self.action60.setCheckable(True)
        self.action60.setObjectName("action60")
        self.actionCustom = QtGui.QAction(MainWindow)
        self.actionCustom.setCheckable(True)
        self.actionCustom.setObjectName("actionCustom")
        self.actionSet_Recording_Countdown = QtGui.QAction(MainWindow)
        self.actionSet_Recording_Countdown.setObjectName("actionSet_Recording_Countdown")
        self.actionImport_Directory = QtGui.QAction(MainWindow)
        self.actionImport_Directory.setObjectName("actionImport_Directory")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionImport_Image_Sequence = QtGui.QAction(MainWindow)
        self.actionImport_Image_Sequence.setObjectName("actionImport_Image_Sequence")
        self.actionImport_Directory = QtGui.QAction(MainWindow)
        self.actionImport_Directory.setObjectName("actionImport_Directory")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExport_To_FCP = QtGui.QAction(MainWindow)
        self.actionExport_To_FCP.setObjectName("actionExport_To_FCP")
        self.actionExport_To_Premiere = QtGui.QAction(MainWindow)
        self.actionExport_To_Premiere.setObjectName("actionExport_To_Premiere")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionImport_Image_Sequence)
        self.menuFile.addAction(self.actionImport_Directory)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionExport_To_FCP)
        self.menuFile.addAction(self.actionExport_To_Premiere)
        self.menuFPS.addAction(self.action24)
        self.menuFPS.addAction(self.action25)
        self.menuFPS.addAction(self.action48)
        self.menuFPS.addAction(self.action30)
        self.menuFPS.addAction(self.action50)
        self.menuFPS.addAction(self.action60)
        self.menuFPS.addAction(self.actionCustom)
        self.menuOptions.addAction(self.menuFPS.menuAction())
        self.menuOptions.addAction(self.actionSet_Recording_Countdown)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        MainWindow.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: rgb(50, 50, 50);color: rgb(255, 255, 255);selection-background-color:rgb(140, 140, 140)", None, QtGui.QApplication.UnicodeUTF8))
        self.timeLabel.setText(QtGui.QApplication.translate("MainWindow", "9999/9999", None, QtGui.QApplication.UnicodeUTF8))
        self.recordBtn.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: rgb(70, 70, 70);", None, QtGui.QApplication.UnicodeUTF8))
        self.recordBtn.setText(QtGui.QApplication.translate("MainWindow", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.playBtn.setStyleSheet(QtGui.QApplication.translate("MainWindow", "background-color: rgb(70, 70, 70);", None, QtGui.QApplication.UnicodeUTF8))
        self.playBtn.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.curTimeLabel.setText(QtGui.QApplication.translate("MainWindow", "00:00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Press Space to advance frame", None, QtGui.QApplication.UnicodeUTF8))
        self.timingBox.setText(QtGui.QApplication.translate("MainWindow", "Record Timing", None, QtGui.QApplication.UnicodeUTF8))
        self.audioBox.setText(QtGui.QApplication.translate("MainWindow", "Record Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOptions.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFPS.setTitle(QtGui.QApplication.translate("MainWindow", "FPS", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Image_Sequence.setText(QtGui.QApplication.translate("MainWindow", "Import Image Sequence...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.action24.setText(QtGui.QApplication.translate("MainWindow", "Film (24 fps)", None, QtGui.QApplication.UnicodeUTF8))
        self.action25.setText(QtGui.QApplication.translate("MainWindow", "PAL (25 fps)", None, QtGui.QApplication.UnicodeUTF8))
        self.action30.setText(QtGui.QApplication.translate("MainWindow", "NTSC (30 fps)", None, QtGui.QApplication.UnicodeUTF8))
        self.action48.setText(QtGui.QApplication.translate("MainWindow", "Show (48 fps)", None, QtGui.QApplication.UnicodeUTF8))
        self.action50.setText(QtGui.QApplication.translate("MainWindow", "PAL Field (50 fps)", None, QtGui.QApplication.UnicodeUTF8))
        self.action60.setText(QtGui.QApplication.translate("MainWindow", "NTSC Field (60 fps)", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCustom.setText(QtGui.QApplication.translate("MainWindow", "Custom...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSet_Recording_Countdown.setText(QtGui.QApplication.translate("MainWindow", "Set Recording Countdown...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Directory.setText(QtGui.QApplication.translate("MainWindow", "Import Directory...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Image_Sequence.setText(QtGui.QApplication.translate("MainWindow", "Import Image Sequence...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImport_Directory.setText(QtGui.QApplication.translate("MainWindow", "Import Directory...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_As.setText(QtGui.QApplication.translate("MainWindow", "Save As...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_To_FCP.setText(QtGui.QApplication.translate("MainWindow", "Export to Final Cut Pro...", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport_To_Premiere.setText(QtGui.QApplication.translate("MainWindow", "Export to Premiere...", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

